name: mysite
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^3.1.0
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  dio: ^3.0.10
  url_strategy: ^0.2.0
  http: ^0.12.2
  flutter_spinkit: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/raleway/Raleway-Bold.ttf
        - asset: assets/raleway/Raleway-Regular.ttf
        - asset: assets/raleway/Raleway-Light.ttf
    - family: Disciplina
      fonts:
        - asset: assets/disciplina/Disciplina.ttf
    - family: SansPosterBold
      fonts:
        - asset: assets/sans-poster-bold/SansPosterBold.ttf
    - family: Rucas
      fonts:
        - asset: assets/rucas/RUCAS.ttf